"""
Phase 6 — PDF Reports.

Generates a formatted incident report PDF for a single scan, suitable for
attaching to a cybercrime complaint (e.g. on cybercrime.gov.in / NCRP).
"""
import os
import datetime as dt
from xml.sax.saxutils import escape as xml_escape

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors

from . import models

REPORTS_DIR = (
    "/tmp/generated_reports" if os.environ.get("VERCEL") else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data", "generated_reports"
    )
)
os.makedirs(REPORTS_DIR, exist_ok=True)


def _safe(text: str) -> str:
    """
    Escape text before handing it to ReportLab's Paragraph, which interprets
    its input as a small XML/HTML-like markup language. Scanned content
    (input_preview, AI summary/advice) is attacker-influenced -- a phishing
    SMS or page can contain '<', '>', or '&' -- so this must always be
    escaped or PDF generation can throw or render incorrectly.
    """
    return xml_escape(text or "")


def _risk_color(score: int):
    if score >= 80:
        return colors.HexColor("#dc2626")
    if score >= 60:
        return colors.HexColor("#f97316")
    if score >= 31:
        return colors.HexColor("#fbbf24")
    return colors.HexColor("#22c55e")


def generate_scan_report_pdf(history_item: models.ScanHistory, user: models.User) -> str:
    filename = f"NexusShield_Report_{history_item.id[:8]}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("NSTitle", parent=styles["Title"], textColor=colors.HexColor("#0f172a"))
    heading_style = ParagraphStyle("NSHeading", parent=styles["Heading2"], textColor=colors.HexColor("#1e293b"), spaceBefore=14)
    body_style = ParagraphStyle("NSBody", parent=styles["Normal"], fontSize=10.5, leading=15)

    story = []
    story.append(Paragraph("NexusShield — Scam Analysis Report", title_style))
    story.append(Paragraph(
        f"Generated {dt.datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')} for {_safe(user.email)}",
        body_style,
    ))
    story.append(Spacer(1, 16))

    # Summary table
    risk_cell_style = ParagraphStyle("Risk", parent=body_style, textColor=_risk_color(history_item.risk_score))
    summary_data = [
        ["Scan Type", _safe(history_item.scan_type.title())],
        ["Scam Category", _safe(history_item.category)],
        ["Detected Scam Type", _safe(history_item.scam_type)],
        ["Risk Score", Paragraph(f"<b>{history_item.risk_score}/100</b>", risk_cell_style)],
        ["Date Scanned", history_item.created_at.strftime("%d %b %Y, %H:%M UTC")],
        ["Matched Known Scam Database", "Yes" if history_item.matched_known_scam else "No"],
    ]
    table = Table(summary_data, colWidths=[2.2 * inch, 4 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("What was scanned", heading_style))
    story.append(Paragraph(_safe(history_item.input_preview) or "(not recorded)", body_style))

    story.append(Paragraph("AI Summary", heading_style))
    story.append(Paragraph(_safe(history_item.summary) or "—", body_style))

    if history_item.red_flags:
        story.append(Paragraph("Red Flags Identified", heading_style))
        for f in history_item.red_flags:
            flag = _safe(f.get("flag", "") if isinstance(f, dict) else str(f))
            detail = _safe(f.get("detail", "") if isinstance(f, dict) else "")
            line = f"<b>{flag}</b> — {detail}" if detail else f"<b>{flag}</b>"
            story.append(Paragraph(f"• {line}", body_style))

    story.append(Paragraph("Recommended Action", heading_style))
    story.append(Paragraph(_safe(history_item.advice) or "—", body_style))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report was generated by NexusShield's AI analysis engine and is intended to support, "
        "not replace, an official cybercrime complaint. To file a complaint in India, visit "
        "cybercrime.gov.in or call the national cybercrime helpline at 1930.",
        ParagraphStyle("Disclaimer", parent=body_style, fontSize=8.5, textColor=colors.HexColor("#64748b")),
    ))

    doc.build(story)
    return filepath
